image: moussavdb/yildiz-build-image

pipelines:
  default:
    - step:
        script:
          - openssl aes-256-cbc -pass pass:$OPENSSL_PWD -in private-key.gpg.enc -out private-key.gpg -d
          - gpg --import private-key.gpg
          - mvn -V -B -s settings.xml deploy
